/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import styles from './PortfolioPage.module.css';

const Footer = () => {
  return (
    <div className={styles.footer}>
      <div className={styles.mehmetAkifKarasu2020}>
        Mehmet Akif Karasu ⏤ 2020
        <br />
      </div>
      <div className={styles.div14}>
        <div className={styles.artstation}>
          Artstation
          <br />
        </div>
        <div>Linkedin</div>
        <div>Twitter</div>
      </div>
    </div>
  );
};

export default Footer;