/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./PortfolioPage.module.css";

const Introduction = () => {
  return (
    <div className={styles.div3}>
      <div className={styles.div4}>
        <div className={styles.column}>
          <div className={styles.helloImMehmetAkif}>
            Hello, I'm Mehmet Akif.
            <br />
          </div>
        </div>
        <div className={styles.column2}>
          <div
            className={
              styles.aSeniorYearDesignStudentWhoTryingToSpecializeIn3DModelingTexturing
            }
          >
            <span style={{ color: "rgba(96,96,96,1)" }}>
              A senior-year design student who trying to specialize in 3D
              modeling & texturing.
            </span>
            <br />
            <br />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Introduction;
