/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./PortfolioPage.module.css";

const NavigationBar = () => {
  return (
    <div className={styles.navigationBar}>
      <img
        loading="lazy"
        src="http://b.io/ext_3-"
        className={styles.img}
        alt="Logo"
      />
      <div className={styles.div2}>
        <div className={styles.work}>Work</div>
        <div className={styles.about}>About</div>
        <div className={styles.playground}>Playground</div>
        <div className={styles.contact}>Contact</div>
      </div>
    </div>
  );
};

export default NavigationBar;
