/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./PortfolioPage.module.css";
import NavigationBar from "./NavigationBar";
import Introduction from "./Introduction";
import ProjectSection from "./ProjectSection";
import Footer from "./Footer";

const PortfolioPage = () => {
  return (
    <div className={styles.portfolioWorkPage}>
      <div className={styles.div}>
        <NavigationBar />
        <Introduction />
        <img
          loading="lazy"
          src="http://b.io/ext_4-"
          className={styles.img2}
          alt="Decorative element"
        />
        <ProjectSection
          number="01"
          title="PROJECT NAME"
          description="Goblin concept digital sculpture with human-like skin. Learned a lot of quick tips and look development."
          details="Sculpted in ZBrush, Retopologized and UVs done in Maya, Textured in Mari, Rendered using Arnold."
          linkText="More shots from this project ↗"
        />
        <div className={styles.seperator} />
        <ProjectSection
          number="02"
          title="PROJECT NAME"
          description="Subsurface weight, specular roughness, diffuse maps generated with the procedure and manual techniques."
          linkText="See case study →"
        />
        <div className={styles.seperator2} />
        <ProjectSection
          number="03"
          title="PROJECT NAME"
          description="Experimental creature modeling for school project."
          linkText="Project WIP"
          linkStyle={styles.link3}
        />
        <div className={styles.seperator} />
        <Footer />
      </div>
      
    </div>
  );
};

export default PortfolioPage;
