/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./PortfolioPage.module.css";

const ProjectSection = ({
  number,
  title,
  description,
  details,
  linkText,
  linkStyle,
}) => {
  return (
    <div className={styles.div5}>
      <div className={styles.div6}>
        <div className={styles.column3}>
          <div className={styles.div7}>
            <div>
              {number} / {title}
            </div>
            <div
              className={
                styles.goblinConceptDigitalSculptureWithHumanLikeSkinLearnedALotOfQuickTipsAndLookDevelopment
              }
            >
              <span style={{ color: "rgba(24,23,23,1)" }}>{description}</span>
              <br />
              <br />
              <br />
            </div>
            {details && (
              <div
                className={
                  styles.sculptedInZBrushRetopologizedAndUVsDoneInMayaTexturedInMariRenderedUsingArnold
                }
              >
                {details}
              </div>
            )}
            <div className={linkStyle || styles.link}>{linkText}</div>
          </div>
        </div>
        <div className={styles.column4}>
          <div className={styles.thumbnail} />
        </div>
      </div>
    </div>
  );
};

export default ProjectSection;
